<?php
namespace app\controllers;
use app\models\setting\Metadata;
use yii\web\Controller;
use yii\caching\DbDependency;
use Yii;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //元数据
        $dependency = new DbDependency([
            'sql' => 'select updated_at from {{%metadata}} where id=1',
        ]);


        $cache = Yii::$app->cache;
        $metaKey = 'metadata';
        $metadata = $cache->getOrSet($metaKey, function () {
            return Metadata::findOne(1);
        },7200, $dependency);

        $this->view->params['keywords'] = $metadata['keywords'];
        $this->view->params['description'] = $metadata['description'];
        $this->view->params['name'] = $metadata['name'];
    }
}